---
- name: Create a directory for storing Ansible facts
  file:
    path: /etc/ansible/facts.d
    state: directory

- name: Store the installed coin's version as an Ansible fact
  copy:
    content: "{'{{ coind_name }}_version': '{{ coind_version }}'}"
    dest: "/etc/ansible/facts.d/coind_{{ coind_name }}.fact"
