---
- hosts: all
  become: yes
  roles:
    - idolactivities.coind
  vars:
    coind_config_global:
      testnet: 1
      server: 1
      rpcauth:
        - "apiuser:69c355a0ffcb1e5108d2539a607c38e8$40078288541643c12247e8e3309fefc314c85bc9608bbdbb188f0f8997bba223"
      rpcuser: apiuser
      rpcpassword: apipass
    coind_config_test:
      rpcbind: 0.0.0.0
      rpcallowip: 0.0.0.0/0
      # Intentionally configure bitcoind to connect to an invalid node so that
      # coind does not consume bandwidth to sync the block database. This is
      # mainly to prevent developers on Comcast (and other ISPs with bandwidth
      # limits) from hitting their bandwidth cap accidentally.
      #
      # Comment this line out if you intend to use this Vagrantfile for
      # integration testing with other software.  For the purposes of testing
      # this role itself, we don't really need to download the block database,
      # thus this artificial handicap should be fine for most.
      connect: 127.0.0.1:1234
    coind_install_cli: yes
    coind_offline_install: yes

# This deploys an instance of the latest version of bitcoind running on
# testnet, enables and configures the RPC API with a user, opens it to the
# entire address space, and installs bitcoin-cli. Test with:
#
#     bitcoin-cli -rpcuser=apiuser -rpcpass=apipass getnetworkinfo
